# Generated by Django 3.1.5 on 2021-07-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=200, null=True)),
                ('Author', models.CharField(max_length=200, null=True)),
                ('Genre', models.CharField(max_length=200, null=True)),
                ('Language', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
